----------------------------------------------------
Running Python linter against following directories:
f8a_auth tests
----------------------------------------------------

Using base prefix '/usr'
New python executable in /home/ptisnovs/bayesian/fabric8-analytics-common/dashboard/repositories/fabric8-analytics-auth/venv/bin/python3
Not overwriting existing python script /home/ptisnovs/bayesian/fabric8-analytics-common/dashboard/repositories/fabric8-analytics-auth/venv/bin/python (you must use /home/ptisnovs/bayesian/fabric8-analytics-common/dashboard/repositories/fabric8-analytics-auth/venv/bin/python3)
Installing setuptools, pip, wheel...done.
Running virtualenv with interpreter /home/ptisnovs/bayesian/fabric8-analytics-common/dashboard/venv/bin/python3
Requirement already satisfied: pycodestyle in ./venv/lib/python3.6/site-packages (2.4.0)
f8a_auth/__init__.py
    Pass
f8a_auth/f8a_auth.py
f8a_auth/f8a_auth.py:240:1: W391 blank line at end of file
    Fail
f8a_auth/errors.py
    Pass
tests/test_errors_class.py
    Pass
tests/test_user_class.py
    Pass
tests/tests.py
    Pass
tests/test_token_handling.py
    Pass

----------------------------------------------------
Running Python linter against selected files:
setup.py
----------------------------------------------------
setup.py
    Pass
Linter fail, 1 source files out of 8 source files need to be fixed
